#!/usr/bin/env node
var reporter = require('nodeunit').reporters.default;
var args = process.argv;
args.shift();
args.shift();

if(args.length > 0){
	args.forEach(function(i){console.log(i)});
	reporter.run(args);
}

